### ISSUE TITLE
Moonlight-OSMC is not configured.

### ISSUE THREAD

**Issue by KillerXtreme-** [dodslaser/moonlight-osmc#12]
I keep getting this error message when I try to run the program after I configure it. The settings don't seem to want to save. It'll show the IP when I click the IP area, then it'll land in the box, but after I hit OK then Run it tells me its not configured.

**Comment by dodslaser** [comment]
Hi! I'm not actively developing this add-on any more. I am (when I have the time) working on CEC support for the moonlight binary in OSMC, which I think is a more elegant approach, but I can't give any timeframe on when that will be out.

In the meantime I suggest you check out @wacker91 and his Luna project. It's a way more complex launching system than what I'm going for, but I've heard it is working fine.
