### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by TimWillebrands** [dodslaser/moonlight-osmc#4]
I just tried to install, but I get this error:

osmc@osmc:~/Moonlight$ sudo apt-get install moonlight-osmc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moonlight-osmc : Depends: moonlight-embedded but it is not installable
E: Unable to correct problems, you have held broken packages.

Do I need to build/install moonlight-embedded myself?

**Comment by dodslaser** [comment]
Since moonlight-embedded has osmc support now I don't provide a copy in my repo anymore. You need to add irtimmers repo to `sources.list`.
